# CVE-2015-3431

This is a PoC exploit for CVE-2015-3431 Arbitrary Remote Code Execution in Pydio < 6.0.7

if I can get it working...I know where the vuln is...just need to get this ish working

```
/pydio/plugins/meta.mount/class.FilesystemMounter.php
```

so..current progress:

```
[*] grabbing secure token
[+] parsed token: 3Q2OBxxRLGGoZh26qMKti4DHMvwhaXcB
[*] trying to authenticate with provided creds
	username: (admin)
	password: (passw0rd)
[*] making initial GET request
[*] making login POST request
[+] session auth'd successfully
[*] attempting to touch (http://192.168.56.101/pydio/plugins/meta.mount/class.FilesystemMounter.php)
[+] response:
	Access not allowed
```

the diff that made me all warm and fuzzy contains some juicy lines:

**example a**

```
-        $cmd = ($MOUNT_SUDO? "sudo ": ""). "mount -t " .$MOUNT_TYPE. (empty( $MOUNT_OPTIONS )? " " : " -o " .$MOUNT_OPTIONS. " " ) .$UNC_PATH. " " .$MOUNT_POINT;
+        $cmd = ($MOUNT_SUDO? "sudo ": ""). "mount -t " .$MOUNT_TYPE. (empty( $MOUNT_OPTIONS )? " " : " -o " .escapeshellarg($MOUNT_OPTIONS). " " ) .escapeshellarg($UNC_PATH). " " .escapeshellarg($MOUNT_POINT);
```

**example b**

```
-        system(($MOUNT_SUDO?"sudo":"")." umount ".$MOUNT_POINT, $res);
+        system(($MOUNT_SUDO?"sudo":"")." umount ".escapeshellarg($MOUNT_POINT), $res);
```

However, as we can see, we are unable to just access that file and throw args at it (even with auth). These directives seem to come from internal state set per user (or by admin?). So I think we need to dive a little further into what the `FilesystemMounter.php` file serves in the `meta.mount` plugin functionality.

